defaults:
    - _self_
    - training: autoencoder
    - override hydra/job_logging: stdout

hydra:
    output_subdir: null
    run:
        dir: .

paths:
    root: ${oc.env:BLISS_HOME}
    data: ${paths.root}/data
    project: ${paths.root}/case_studies/galsim_galaxies
    output: ${paths.project}/output

mode: train

get_data:
    seed: 42
    n_samples: 30000
    ds_name: single_gal
    overwrite: False

single_galaxy_datasets:
    single_galaxies:
        _target_: bliss.datasets.single_galaxies.SingleGalsimGalaxies
        catalog_file: ${paths.data}/OneDegSq.fits
        slen: 53
        seed: ${get_data.seed} # for btk
    train_saved_single_galaxies:
        _target_: bliss.datasets.single_galaxies.SavedSingleGalsimGalaxies
        dataset_file: ${paths.project}/data/train_single_galaxies.pt
        epoch_size: 10000
    val_saved_single_galaxies:
        _target_: bliss.datasets.single_galaxies.SavedSingleGalsimGalaxies
        dataset_file: ${paths.project}/data/val_single_galaxies.pt
        epoch_size: 10000
    single_galaxies_datamodule:
        _target_: bliss.datasets.saved.SavedDataModule
        train_ds: ${single_galaxy_datasets.train_saved_single_galaxies}
        val_ds: ${single_galaxy_datasets.val_saved_single_galaxies}
        batch_size: 64

blends_datasets:
    blends:
        _target_: bliss.datasets.blends.GalsimBlends
        catalog_file: ${paths.data}/OneDegSq.fits
        stars_file: ${paths.data}/stars_med_june2018.fits
        tile_slen: 4
        max_sources_per_tile: 1
        slen: 40
        bp: 24
        seed: ${get_data.seed} # for btk
    train_saved_blends:
        _target_: bliss.datasets.blends.SavedGalsimBlends
        dataset_file: ${paths.project}/data/train_blends.pt
        epoch_size: 10000
    val_saved_blends:
        _target_: bliss.datasets.blends.SavedGalsimBlends
        dataset_file: ${paths.project}/data/val_blends.pt
        epoch_size: 10000
    blends_datamodule:
        _target_: bliss.datasets.saved.SavedDataModule
        train_ds: ${blends_datasets.train_saved_blends}
        val_ds: ${blends_datasets.val_saved_blends}
        batch_size: 32

models:
    decoder:
        _target_: bliss.models.decoder.ImageDecoder
        n_bands: 1
        tile_slen: 4
        ptile_slen: 52
        psf_slen: 25
        border_padding: 24
        galaxy_model:
            _target_: bliss.models.galaxy_net.OneCenteredGalaxyAE
            slen: ${models.galaxy_net.slen}
            latent_dim: ${models.galaxy_net.latent_dim}
            hidden: ${models.galaxy_net.hidden}
            n_bands: ${models.galaxy_net.n_bands}
            ckpt: ${paths.project}/models/autoencoder.pt
    galaxy_net:
        _target_: bliss.models.galaxy_net.OneCenteredGalaxyAE
        slen: 53
        latent_dim: 8
        hidden: 256
        n_bands: 1
        optimizer_params:
            lr: 1e-3
    detection_encoder:
        _target_: bliss.models.detection_encoder.DetectionEncoder
        input_transform:
            _target_: bliss.models.detection_encoder.ConcatBackgroundTransform
        n_bands: 1
        tile_slen: 4
        ptile_slen: 52
        max_detections: 1
        channel: 8
        spatial_dropout: 0.0
        dropout: 0.0
        hidden: 128
        annotate_probs: True
        slack: 1.0
        optimizer_params:
            lr: 1e-4
    binary_encoder:
        _target_: bliss.models.binary_encoder.BinaryEncoder
        input_transform:
            _target_: bliss.models.detection_encoder.ConcatBackgroundTransform
        n_bands: 1
        tile_slen: 4
        ptile_slen: 52
        channel: 8
        hidden: 128
        spatial_dropout: 0.0
        dropout: 0.0
        optimizer_params:
            lr: 1e-4
    galaxy_encoder:
        _target_: bliss.models.galaxy_encoder.GalaxyEncoder
        decoder: ${models.decoder}
        autoencoder: ${models.galaxy_net}
        hidden: ${models.galaxy_net.hidden}
        optimizer_params:
            lr: 1e-3

training:
    n_epochs: 1
    experiment: null
    version: null
    save_top_k: 3
    weight_save_path: ${paths.project}/models/${training.name}.pt
    seed: 42
    trainer:
        _target_: pytorch_lightning.Trainer
        logger: True
        enable_checkpointing: False
        reload_dataloaders_every_n_epochs: 0
        max_epochs: ${training.n_epochs}
        min_epochs: ${training.n_epochs}
        accelerator: "gpu"
        devices: 1
        limit_train_batches: 1.0
        limit_val_batches: 1.0
        check_val_every_n_epoch: 1
        log_every_n_steps: 50
        accumulate_grad_batches: 1

plots:
    figs:
        - "single_gal"
        - "blend_gal"
        - "toy"
    checkpoints:
        detection_encoder: ${paths.project}/models/detection_encoder.pt
        galaxy_encoder: ${paths.project}/models/galaxy_encoder.pt
        binary_encoder: ${paths.project}/models/binary_encoder.pt
        autoencoder: ${paths.project}/models/autoencoder.pt
    cachedir: ${paths.project}/output/galsim_figs_cache
    figdir: ${paths.project}/figures
    image_format: "png"
    overwrite: false
    device: "cuda:0"
    encoder:
        n_images_per_batch: 10
        n_rows_per_batch: 15
    test_datasets:
        single_galaxies: ${paths.project}/data/test_single_galaxies.pt
        blends: ${paths.project}/data/test_blends.pt
