# @package _global_
training:
  name: "detection_encoder"
  model: ${models.detection_encoder}
  dataset: ${blends_datasets.blends_datamodule}
  n_epochs: 1001
  trainer:
    enable_checkpointing: True
