# @package _global_
training:
    name: "galaxy_encoder"
    model: ${models.galaxy_encoder}
    dataset: ${blends_datasets.blends_datamodule}
    n_epochs: 2001
    trainer:
        enable_checkpointing: True
        check_val_every_n_epoch: 50
